export default {
    extends: ['stylelint-config-recommended-scss'],

    ignoreFiles: ['_site/**', 'vendor/**'],

    plugins: ['stylelint-order'],

    rules: {
        'selector-max-id': 0,
        'length-zero-no-unit': true,
        'color-hex-length': 'short',
        'shorthand-property-no-redundant-values': true,

        'order/properties-order': [
            [
                {
                    groupName: 'position',
                    emptyLineBefore: 'always',
                    noEmptyLineBetween: true,
                    properties: [
                        'position',
                        'inset',
                        'inset-block',
                        'inset-block-start',
                        'inset-block-end',
                        'inset-inline',
                        'inset-inline-start',
                        'inset-inline-end',
                        'top',
                        'right',
                        'bottom',
                        'left',
                        'z-index',
                    ],
                },
                {
                    groupName: 'box_model',
                    emptyLineBefore: 'always',
                    noEmptyLineBetween: true,
                    properties: [
                        'display',
                        'flex',
                        'flex-grow',
                        'flex-shrink',
                        'flex-basis',
                        'flex-flow',
                        'flex-direction',
                        'flex-wrap',
                        'order',
                        'grid',
                        'grid-template',
                        'grid-template-areas',
                        'grid-template-rows',
                        'grid-template-columns',
                        'grid-auto-flow',
                        'grid-auto-rows',
                        'grid-auto-columns',
                        'grid-area',
                        'grid-row',
                        'grid-row-start',
                        'grid-row-end',
                        'grid-column',
                        'grid-column-start',
                        'grid-column-end',
                        'place-content',
                        'align-content',
                        'justify-content',
                        'place-items',
                        'align-items',
                        'justify-items',
                        'place-self',
                        'align-self',
                        'justify-self',
                        'gap',
                        'row-gap',
                        'column-gap',
                        'float',
                        'clear',
                        'box-sizing',
                        'width',
                        'min-width',
                        'max-width',
                        'height',
                        'min-height',
                        'max-height',
                        'aspect-ratio',
                        'padding',
                        'padding-block',
                        'padding-block-start',
                        'padding-block-end',
                        'padding-inline',
                        'padding-inline-start',
                        'padding-inline-end',
                        'padding-top',
                        'padding-right',
                        'padding-bottom',
                        'padding-left',
                        'margin',
                        'margin-block',
                        'margin-block-start',
                        'margin-block-end',
                        'margin-inline',
                        'margin-inline-start',
                        'margin-inline-end',
                        'margin-top',
                        'margin-right',
                        'margin-bottom',
                        'margin-left',
                        'overflow',
                        'overflow-x',
                        'overflow-y',
                        'overscroll-behavior',
                        'overscroll-behavior-x',
                        'overscroll-behavior-y',
                    ],
                },
                {
                    groupName: 'typography',
                    emptyLineBefore: 'always',
                    noEmptyLineBetween: true,
                    properties: [
                        'font',
                        'font-family',
                        'font-size',
                        'font-style',
                        'font-weight',
                        'font-variant',
                        'line-height',
                        'letter-spacing',
                        'word-spacing',
                        'color',
                        'text-align',
                        'text-decoration',
                        'text-indent',
                        'text-transform',
                        'text-overflow',
                        'white-space',
                        'word-break',
                        'overflow-wrap',
                        'list-style',
                        'list-style-type',
                        'list-style-position',
                        'list-style-image',
                        'src',
                        'font-display',
                    ],
                },
                {
                    groupName: 'visual',
                    emptyLineBefore: 'always',
                    noEmptyLineBetween: true,
                    properties: [
                        'background',
                        'background-color',
                        'background-image',
                        'background-position',
                        'background-size',
                        'background-repeat',
                        'background-origin',
                        'background-clip',
                        'background-attachment',
                        'border',
                        'border-width',
                        'border-style',
                        'border-color',
                        'border-top',
                        'border-right',
                        'border-bottom',
                        'border-left',
                        'border-radius',
                        'outline',
                        'outline-width',
                        'outline-style',
                        'outline-color',
                        'outline-offset',
                        'box-shadow',
                    ],
                },
                {
                    groupName: 'others',
                    emptyLineBefore: 'always',
                    noEmptyLineBetween: true,
                    properties: [
                        'content',
                        'visibility',
                        'opacity',
                        'appearance',
                        'cursor',
                        'pointer-events',
                        'user-select',
                        'filter',
                        'backdrop-filter',
                        'transform',
                        'transform-origin',
                        'animation',
                        'animation-name',
                        'animation-duration',
                        'animation-timing-function',
                        'animation-delay',
                        'animation-iteration-count',
                        'animation-direction',
                        'animation-fill-mode',
                        'animation-play-state',
                        'transition',
                        'transition-property',
                        'transition-duration',
                        'transition-timing-function',
                        'transition-delay',
                    ],
                },
            ],
            {
                unspecified: 'bottom',
                emptyLineBeforeUnspecified: 'always',
            },
        ],
    },
};
